version: "3.9"

services:
  ml:
    build: .
    container_name: fake-apk-ml
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - ./:/app
      - ./artifacts:/app/artifacts
      - ./models:/app/models
    command: uvicorn ml.infer_service:app --host 0.0.0.0 --port 9000 --log-level warning --no-access-log

  streamlit:
    build: .
    container_name: fake-apk-ui
    env_file:
      - .env
    environment:
      - ML_SERVICE_URL=http://ml:9000
    depends_on:
      - ml
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    command: streamlit run ml/streamlit_app.py --server.port 8501 --server.address 0.0.0.0

networks:
  default:
    name: fake-apk-net

