services:
  ml:
    build: .
    container_name: fake-apk-ml
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - ./:/app
      - ./artifacts:/app/artifacts
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: "2.0"
        reservations:
          memory: 2G
          cpus: "1.0"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: uvicorn ml.infer_service:app --host 0.0.0.0 --port 9000 --log-level info --timeout-keep-alive 120 --workers 1

  streamlit:
    build: .
    container_name: fake-apk-ui
    env_file:
      - .env
    environment:
      - ML_SERVICE_URL=http://ml:9000
    depends_on:
      ml:
        condition: service_started
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"
        reservations:
          memory: 1G
          cpus: "0.5"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: streamlit run ml/streamlit_app.py --server.port 8501 --server.address 0.0.0.0

networks:
  default:
    name: fake-apk-net
